#!/usr/bin/expect
spawn ssh <CNetID>@midway2.rcc.uchicago.edu
expect "*assword:"                          
send "YOUR_PASSWORD\r"
expect "Passcode or option (1-3): "
send "1\r"
expect "$ "
send "cd ~/lsda\r"
expect "$ "
send "sinteractive --exclusive --account=cmsc25025 --time=4:00:00 --mem=4000\r"
expect "$ "
send "/project/cmsc25025/run_ipython.sh Anaconda3\r"
interact
